labels = {'SteadyState','SteadyState+LowCaoAPFeats','SteadyState+LowCao14Feats','SteadyState+HighCaoAPFeats','SteadyState+HighCao14Feats'};
%% IKr Block Prediction Performance 
datasets = {'SteadyState_APFeatures_IKrBlock'...
    'SteadyState_APFeatures_LowCao_APFeatures_IKrBlock'...
    'SteadyState_APFeatures_LowCao_14Features_IKrBlock'...
    'SteadyState_APFeatures_HighCao_APFeatures_IKrBlock'...
    'SteadyState_APFeatures_HighCao_14Features_IKrBlock'};
plotML(datasets,labels)
%% ICaL Increase Prediction Performance 
datasets = {'SteadyState_APFeatures_ICaLIncrease'...
    'SteadyState_APFeatures_LowCao_APFeatures_ICaLIncrease'...
    'SteadyState_APFeatures_LowCao_14Features_ICaLIncrease'...
    'SteadyState_APFeatures_HighCao_APFeatures_ICaLIncrease'...
    'SteadyState_APFeatures_HighCao_14Features_ICaLIncrease'};
plotML(datasets,labels)
